import Header from './components/Header';
import './globals.css';

import { Poppins } from 'next/font/google';

const poppins = Poppins({
	weight: ['100', '300', '400', '600'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'NextJS 13 Course',
	description: 'Generated by create next app',
	keywords:
		'web development, web design, javascript, react, node, angular, vue, html, css',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<Header />
				<main className="container">{children}</main>
			</body>
		</html>
	);
}
